day1 = input("What is your birthday (for example, 11th Jan 2022)? ")
day2 = input("What is friend number 1's birthday (for example, 11th Jan 2022)? ")
day3 = input("What is friend number 2's birthday (for example, 11th Jan 2022)? ")
day4 = input("What is friend number 3's birthday (for example, 11th Jan 2022)? ")
day5 = input("What is friend number 4's birthday (for example, 11th Jan 2022)? ")
print("Your birthday is {0}".format(day1))
print("Your friend number 1's day is {0}".format(day2))
print("Your friend number 2's day is {0}".format(day3))
print("Your friend number 3's day is {0}".format(day4))
print("Your friend number 4's day is {0}".format(day5))